# Generated by Django 4.0.4 on 2022-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_rename_items_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('brand', models.CharField(max_length=120)),
                ('number_of_order', models.IntegerField()),
            ],
        ),
    ]
