# Generated by Django 4.0.4 on 2022-05-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='number_of_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
