# Generated by Django 4.0.4 on 2022-05-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_remove_cart_brand_remove_cart_number_of_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
    ]
